modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/Default-Amplified-Biomes-2/issues"
[[mods]]
modId = "defaultamplifiedbiomes2"
version = "1.0"
displayName = "Default Amplified Biomes 2"
displayURL = ""
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
Amplified Biomes in the default world type!
'''
[[dependencies.defaultamplifiedbiomes2]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
